config/routes.rb
Rails.application.routes.draw do
  get 'person/index'
  get 'person/show'
  root 'home#home_page'
  resources  :person
  get "/home/home_page"
  # get "/home/:id", to: "home#show"
  # get "/home/new", to: "home#new"
  resources :home

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/Alog.rb
class Alog < ApplicationRecord
  validates :name, presence: true
  validates :status, acceptance: { accept: ['start', 'mid','complete'] }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/change.rb
class Change < ApplicationRecord
end

app/models/column_change.rb
class ColumnChange < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true, length: { minimum: 10 }
end

app/models/person.rb
class Person < ApplicationRecord
  validates :terms_of_service, acceptance: { message: 'must be abided' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home_page
    @users = Home.all

  end

  def show
    @users = Home.find(params[:id])

  end

  def new
    @users = Home.new

  end

  def create
    @users = Home.new(users_params)

    if @users.save
      redirect_to @users

    else
      render :new
    end
  end

  private
  def users_params
    params.require(:users).permit(:name, :email)

  end

end

app/controllers/person_controller.rb
class PersonController < ApplicationController

  layout 'admin'
  def index
    @person = Person.all

  end

  def show
    @person = Person.find(params[:id])

  end

  def new
    @person= Person.new
  end

  def create
    @person = Person.new(people_params)

    if @p.save
      flash[:notice] = 'Subject Created Successfully....'
      redirect_to (@person)

    else
      render :new

    end
  end

  private

  def people_params
    params.require(:person).permit(:name, :email, :mobile, :date_of_birth, :blood_group)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/home/home_page.html.erb
<h1>Home Page</h1>
<ol>
	<% @users.each do |user| %>
	<li>
		<%= link_to user.name, user %><br/>


		
	</li>
	
   <% end %> 

</ol>
<%= link_to "New Article", new_home_path  %>

app/views/home/new.html.erb
<h1>New User</h1>

<%= form_with model: @homes do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @users.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
       <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
    <% @users.errors.full_messages_for(:email).each do |message| %>
     <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/home/show.html.erb
<h2><%= @users.name %></h2>
<p><%= @users.email %></p>
<p><%= @users.phone %></p>
<p><%= @users.message %></p>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

<% if !flash[:notice].blank? %>
  <div class ="notice">
    <%=flash[:notice] %>
  </div>
<% end %>
<%= yield %>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/person/index.html.erb
<h1>User List</h1>

<ul>
  <% @people.each do |person| %>
    <li>
      <%= link_to person.name, person %>
      </a>
    </li>
  <% end %>
</ul>

<%= link_to("Add new User", 'person/new',:class => 'action new')%>

app/views/person/new.html.erb
<h1>New User</h1>

<%= form_with model:@people do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @person.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @person.errors.full_messages_for(:email).each do |message| %>
    <% end %>
  </div>

  <div>
    <%= form.label :mobile %><br>
    <%= form.text_field :mobile %>
    <% @person.errors.full_messages_for(:mobile).each do |message| %>
    <% end %>
  </div>

  <div>
    <%= form.label :date_of_birth %><br>
    <%= form.text_field :date_of_birth %>
    <% @person.errors.full_messages_for(:date_of_birth).each do |message| %>
    <% end %>
  </div>
  <div>
    <%= form.label :blood_group %><br>
    <%= form.text_field :blood_group %>
    <% @person.errors.full_messages_for(:blood_group).each do |message| %>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/person/show.html.erb
<h1><%= @people.name %></h1>
<p><%= @people.email %></p>
<p><%= @people.mobile %></p>
<p><%= @people.date_of_birth %></p>